[build]
  publish = "kracht/dist"  # Ensure this matches your build output directory
  # Uncomment and adjust the build command if necessary
  # command = "npm run build"  # Example build command; adjust as needed

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200